### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by soloraid** [mrmyroll2/NgScrollPicker#8]
I read your library and saw that You used template method this cause so many issues because of rendering DOM.
I solve this problem with pure pipes.
anther issue is that when I use your ng scroll piicker on dialog or bottom sheet the postion of each slots wrong because of use PageX.
I fixed these issue just need access to push my branches and pull request for merge.
can you give me access to push new branches ?

**Comment by mrmyroll2** [comment]
Great to hear that. I think you can fork and PR. But I have add you as contributor. Feel free to PR.
Happy branching and let's merge those changes! 🌳🔄
